# Generated by Django 6.0.1 on 2026-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
