# Generated by Django 6.0.1 on 2026-01-28 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_city_city_name_en_city_city_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_property', to='house_app.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_photo', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('под самоделку', 'под самоделку'), ('евроремонт', 'евроремонт'), ('хорошее', 'хорошее'), ('среднее', 'среднее'), ('не достроено', 'не достроено')], max_length=32),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('studio', 'studio')], max_length=32),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_photo', to='house_app.property'),
        ),
    ]
